[workspace]
members = [
    "crates/kaalang",
    "crates/kaalang-cli",
    "crates/kaalang-macros",
    "crates/kaalang-model",
    "crates/kaalang-svg",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
kaalang-macros = { path = "crates/kaalang-macros" }
kaalang-model = { path = "crates/kaalang-model" }
kaalang-svg = { path = "crates/kaalang-svg" }

proc-macro2 = "1"
quote = "1"
syn = { version = "3", features = ["full"] }
trybuild = "1"
unicode-segmentation = "1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "deny"

cast_possible_truncation = "allow"
cast_possible_wrap = "allow"
trivially_copy_pass_by_ref = "allow"
struct_field_names = "allow"
pub_underscore_fields = "allow"
