[package]
name = "kaalang"
description = "A visual flow dialect of Rust"
documentation = "https://docs.rs/kaalang"
readme = "../../README.md"
keywords = ["code-visualization", "flowchart", "drakon", "visual-programming", "procedural-macro"]
categories = ["development-tools", "visualization"]
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
kaalang-macros = { workspace = true }

[dev-dependencies]
kaalang-svg = { workspace = true }
trybuild = { workspace = true }

[lints]
workspace = true
