[package]
name = "contour-svg"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
contour-model = { workspace = true }
proc-macro2 = { workspace = true, features = ["span-locations"] }
syn = { workspace = true }

[[bin]]
name = "cargo-contour"
path = "src/main.rs"

[lints]
workspace = true
