[package]
name = "kaalang-macros"
description = "The procedural macro behind the kaalang crate"
documentation = "https://docs.rs/kaalang-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
kaalang-compiler = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
