[package]
name = "kaalang-macros"
description = "Procedural macros for kaalang"
documentation = "https://docs.rs/kaalang-macros"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true

[dependencies]
kaalang-compiler = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
