[package]
name = "kaalang-render"
description = "Structural layout for kaalang diagrams"
documentation = "https://docs.rs/kaalang-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
kaalang-compiler = { workspace = true }

[dev-dependencies]
kaalang-testing = { workspace = true }
syn = { workspace = true }

[lints]
workspace = true
